### ISSUE TITLE
Spell description background is always white, white text is invisible

### ISSUE THREAD

**Issue by d-man9000** [wmak/dndbeyond-darktheme#1]
I'm using this Stylus theme on Opera, and I'm encountering a situation when using white text, it's invisible in the spell description screens.

**Comment by d-man9000** [comment]
Update to the previous, it's only when you're reading the spell description of a known, not prepared spell.

**Comment by wmak** [comment]
@d-man9000 thanks for bringing this to my attention! If you update to version 1.0.8 that should be fixed now, Please feel free to open new issues if you find any!
