### ISSUE TITLE
Boxes aren't dark anymore

### ISSUE THREAD

**Issue by NilsKrause** [wmak/dndbeyond-darktheme#2]
I don't exactly know if dndbeyond changed anything, but all boxes on the website are light despite the theme beeing active. I tracked the source of the background color down to a svg box. But I am not sure if the addon can change the background of the svg's.

Any plans to support the the current website?

This is how it currently looks for me.
![pic-selected-200614-2106-47](https://user-images.githubusercontent.com/15922517/84601829-4c2a2280-ae83-11ea-93bf-a8953f54da52.png)

**Comment by wmak** [comment]
@NilsKrause Hey sorry this took so long, been pretty busy. Just got an initial fix for this out, you should be able to update the theme by clicking the install in the readme.
There's definitely going to be elements I've missed, opening new issues as you see them will be greatly appreciated.
